apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service-deployment
spec:
  selector:
    matchLabels:
      app: rest-service
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
      - name: rest-service
        image: sau2382/rest-service:latest
        ports:
        - containerPort: 80