server:
  port : 8761

spring:
  application:
    name: naming-server 
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
    
management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
        
eureka:
  client: 
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0  