server:
  port : 80
  servlet:
    context-path: /demoservice
spring:
  application:
    name: demo-service  
  config:
    import: optional:configserver:http://localhost:8888?fail-fast=false&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100
    #import: configserver:http://localhost:8888?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100
  cloud:
    config:
      enabled: true
      name: demo-service
      fail-fast: true
      request-connect-timeout: 10
      request-read-timeout: 30
#      retry:
#        max-attempts: 10
#        max-interval: 1500
#        multiplier: 1.2
#        initial-interval: 1100
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     loggers:
      enabled: true
     shutdown:
      enabled: true
      
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    
demoservice:
  log:
    path: logs
    rolloverSize: 1MB
  welcometext: "my app local 1.0"
 

#custom property for enabling log streaming to logstash
logstash:
  enable: false
  ip: 1.2.3.4
  port: 80
  
     