server:
  port : 80
  servlet:
    context-path: /demoservice
spring:
  application:
    name: demo-service  
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     loggers:
      enabled: true
     shutdown:
      enabled: true
      
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    
demoservice:
  log:
    path: logs
    rolloverSize: 1MB
  welcometext: "my app1.0"  

#custom property for enabling log streaming to logstash
logstash:
  enable: false
  ip: 1.2.3.4
  port: 80    
      