server:
  port : 8888

spring:
  application:
    name: spring-cloud-config-server  
  cloud:
    config:
      server:
        git:
          #uri: file:///D:/workspaces/git_local_repo
          uri: https://github.com/sau2382/ConfigRepo
          #basedir: target/config
          default-label: main
          timeout: 10
          search-paths:
            - microservice1
            - microservice2
      enabled: false
              
          
management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
        
logging:
  level:
    #com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'